### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [joepie91/python-whois#128]
Getting this error when requesting an '.as' domain. Raw whois output doesnt look any different from other domains, however im getting index errors.
```
Traceback (most recent call last):
  File myfile.py", line 25, in <module>
    pythonwhois.get_whois('man.as', normalized=[])
  File "/usr/local/lib/python2.7/site-packages/pythonwhois/__init__.py", line 8, in get_whois
    return parse.parse_raw_whois(raw_data, normalized=normalized, never_query_handles=False, handle_server=server_list[-1])
  File "/usr/local/lib/python2.7/site-packages/pythonwhois/parse.py", line 521, in parse_raw_whois
    match = match.split()[0]
IndexError: list index out of range
```
How to fix this in parse.py ?

**Comment by purplehat7** [comment]
+1
