### ISSUE TITLE
library fails parsing .ca domains

### ISSUE THREAD

**Issue by skjortan23** [joepie91/python-whois#145]
When performing a whois for Canadian domains the library crashes with a KeyError.

to reproduce.
`
import pythonwhois
res = pythonwhois.get_whois('cns.ca')
`

error:
`Traceback (most recent call last):
  File "/Users/skjortan/intelliagg/test_pythonwhois.py", line 3, in <module>
    res = pythonwhois.get_whois('cns.ca')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonwhois/__init__.py", line 8, in get_whois
    return parse.parse_raw_whois(raw_data, normalized=normalized, never_query_handles=False, handle_server=server_list[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonwhois/parse.py", line 516, in parse_raw_whois
    data["registrar"].insert(0, match.group(1).strip())
KeyError: 'registrar'
`

**Comment by skjortan23** [comment]
The following code I hacked together to be able to parse .ca domains
It works but its not pretty.

in parse.py 
`		else:
			match = re.search("Registrar:\n\s+Name:(.+)", segment)
			if match is not None:
				data["registrar"] = [match.group(1).strip()]`

**Comment by raeq** [comment]
See forked project:
https://github.com/cuda-networks/python-whois/commits/master

**Comment by skjortan23** [comment]
Hm would be nice if the maintainer of the core library @joepie91 could pull the fixes in the fork. There are fixes for this. Or let me know if you want me to make a pull request with the fix.
