### ISSUE TITLE
Error with new TLD

### ISSUE THREAD

**Issue by laurentdu51** [joepie91/python-whois#25]
Hello, i'm want get whois for new TLD, you can get the liste here : http://www.opensrs.com/site/services/new-tlds/price-list-new-tlds

But i'am have this error : 

root@LHA:~# pwhois ikoula.support
Traceback (most recent call last):
  File "/usr/local/bin/pwhois", line 23, in <module>
    data = pythonwhois.net.get_whois_raw(args.domain[0])
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 61, in get_whois_raw
    return get_whois_raw(domain, referal_server, new_list)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 37, in get_whois_raw
    response = whois_request(request_domain, target_server)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 75, in whois_request
    sock.connect((server, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -2] Name or service not known

Can you solve this error ? 
Thank you

**Comment by joepie91** [comment]
Looks like it's a problem with WHOIS servers that specify a HTTP URL as 'WHOIS referal'. I'll fix this and push an update today or tomorrow.

**Comment by joepie91** [comment]
A new version (2.3.0) with this fix is now available on PyPI. Run `pip install --upgrade pythonwhois` to update. Make sure to read the [update notes](https://github.com/joepie91/python-whois#important-update-notes) prior to updating.

**Comment by laurentdu51** [comment]
Hello, thank you for the fix.

I'am have an annoter bug .

root@LHA:~# pwhois ikeepincloud.buzz
Traceback (most recent call last):
  File "/usr/local/bin/pwhois", line 23, in <module>
    data, server_list = pythonwhois.net.get_whois_raw(args.domain[0], with_server_list=True)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 30, in get_whois_raw
    target_server = get_root_server(domain)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 79, in get_root_server
    raise shared.WhoisException("No root WHOIS server found for domain.")
pythonwhois.shared.WhoisException: No root WHOIS server found for domain.

**Comment by joepie91** [comment]
I just fixed that and released 2.4.1. Run pip install --upgrade pythonwhois to update.

If you run across any more issues, please create a new GitHub issue rather than adding to this one - it makes it easier for me to keep track of what still needs to be done, so that I can make sure I won't forget about any issues.
