### ISSUE TITLE
another domain causing regex issue

### ISSUE THREAD

**Issue by obormot** [joepie91/python-whois#42]
pythonwhois 2.4.3, Python 2.7.5 on Mac OS X
get_whois('kawaihayao.jp') loads the CPU and runs forever; after Ctrl-C here is the traceback:

```
>>> import pythonwhois
>>> pythonwhois.get_whois('kawaihayao.jp')
.....^C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/pythonwhois/__init__.py", line 8, in get_whois
    return parse.parse_raw_whois(raw_data, normalized=normalized, never_query_handles=False, handle_server=server_list[-1])
  File "/lib/python2.7/site-packages/pythonwhois/parse.py", line 558, in parse_raw_whois
    data["contacts"] = parse_registrants(raw_data, never_query_handles, handle_server)
  File "/lib/python2.7/site-packages/pythonwhois/parse.py", line 848, in parse_registrants
    match = re.search(regex, segment)
  File "/lib/python2.7/re.py", line 148, in search
    return _compile(pattern, flags).search(string)
KeyboardInterrupt
>>>
```

**Comment by obormot** [comment]
Well, tried again today and could no longer reproduce the issue. Whois says the record was updated on 2014-9-4 (4 days ago), and now it gets parsed normally.
