### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by PidgeyL** [joepie91/python-whois#76]
Hi Joe, got this little issue going on here. (traceback below).
I'm testing this behind a proxy (at work), so I don't know if that'd be the issue or not, as it requires authentication. However, my python scripts make their way through. Happens both with python 2.7 and 3.4. Does your script not work behind a proxy? Either way, there should be some error handeling. Want me to take care of it?

Pidgey@NorthernSec:~/Git/cve-search$ pwhois cryto.net
Traceback (most recent call last):
  File "/usr/local/bin/pwhois", line 23, in <module>
    data, server_list = pythonwhois.net.get_whois_raw(args.domain[0], with_server_list=True)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 33, in get_whois_raw
    target_server = get_root_server(domain)
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 76, in get_root_server
    data = whois_request(domain, "whois.iana.org")
  File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 86, in whois_request
    sock.connect((server, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 110] Connection timed out

**Comment by joepie91** [comment]
Yeah, I have no idea what could be causing this, to be honest. Could you have a look into why it's happening in your environment (if it _is_ still happening), and whether it'd require changes to python-whois to make it work?
