### ISSUE TITLE
Pythonwhois can't handle .ca

### ISSUE THREAD

**Issue by ran2** [joepie91/python-whois#95]
pwhois google.ca
Traceback (most recent call last):
  File "/usr/local/bin/pwhois", line 33, in <module>
    parsed = pythonwhois.parse.parse_raw_whois(data, normalized=True, never_query_handles=False, handle_server=server_list[-1])
  File "/Library/Python/2.7/site-packages/pythonwhois/parse.py", line 516, in parse_raw_whois
    data["registrar"].insert(0, match.group(1).strip())
KeyError: 'registrar'

**Comment by lolobosse** [comment]
I can confirm the bug, still there also when you use it as a python library
